baseURL = "https://www.taufique.me/"
languageCode = "en-us"
title = "Md. Taufique Hussain"

[params]
    briefTitle = "Taufique"

[menus]
    [[menu.nav]]
        identifier = "research"
        name = "Research"
        title = "Research"
        url = "/research/"
        weight = -120
    [[menu.nav]]
        identifier = "publications"
        name = "Publications"
        title = "Publications"
        url = "/publications/"
        weight = -110
    [[menu.nav]]
        identifier = "posts"
        name = "Posts"
        title = "Posts"
        url = "/posts/"
        weight = -100
    [[menu.nav]]
        identifier = "journal"
        name = "Journal"
        title = "Journal"
        url = "/journal/"
        weight = -90
    [[menu.nav]]
        identifier = "about"
        name = "About Me"
        title = "About Me"
        url = "/about/"
        weight = -80
